// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

console.log("\xf0\x9f\x94\xa5");

console.log("❤️");

function add(x, y) {
  return x + y | 0;
}

console.log("yes");

var abcabc = "abcabc";

var myInt = 123.0;

var myBool = /* true */1;

exports.myInt = myInt;
exports.add = add;
exports.myBool = myBool;
exports.abcabc = abcabc;
/*  Not a pure module */
